### ISSUE TITLE
Data license forbids redistribution

### ISSUE THREAD

**Issue by Mailaender** [opentyrian/opentyrian#18]
http://sites.google.com/a/camanis.net/opentyrian/tyrian/tyrian21.zip is either illegal or the included license file is misleading. https://build.opensuse.org/request/show/829629#revision_details_2

**Comment by carlreinke** [comment]
That license file is the original license, as it was when it was included with retail copies of the game.  In 2004, the game [was offered](https://web.archive.org/web/20140808040448/http://www.freewebs.com/worldtreegames/) under an informal license:

> Feel free to play it all you want and share it with friends, but for the moment I'd like to just have a central backup place (here) for the game.  In the future I might not mind other sites sharing it, but I do enjoy amusing fans. :)

See also [this email](http://members.iinet.net.au/~vannevar/tyrian/) (August 5 2004):

> Hello!
> 
> I'm making up a mass mailing to all the Tyrian friends / fans who have emailed
> me over the past two years.  After giving it some thought, I've decided the best
> thing to do is to just put some things up on a website.
> 
> And of course much procrastination later, I picked a nice web hosting place
> that's free and stuck up a rather quick-and-dirty site.  There'll be more to
> come, and I'll probably try to find a copy of the final Tyrian 2000 game to put
> up for download.
> 
> Hopefully this will become the main repository for downloading the game, as I
> simply feel like keeping tabs on it.  Years of effort and all that. :)  But I
> want people to play it, to which otherwise one would ask why did I bother
> writing it at all?  Well, aside from the royalties that I lived on for a while
> and got me to move out of my parent's house.
> 
> Anyhow, if you're getting this message, you must have emailed me before with a
> question or comment about Tyrian.  And I've saved every one. :)
> 
> I'm off doing Gameboy games now for a weird company called Amaze, which is a lot
> of fun, actually.  Though it does keep me pretty busy a lot of the time.
> 
> Have fun!
> 
> Jason Emery
> World Tree Games
> 
> 
> 
> The site happens to be...
> 
> http://www.freewebs.com/worldtreegames/

As far as I am concerned, redistributing the game files for people to play OpenTyrian follows the spirit of this informal license.  Organizations that must take a conservative legal stance will probably not find this sufficient.

If you need more clarification, you'll have to contact Jason Emery (perhaps via [Twitter](https://mobile.twitter.com/TyrianForever/)).

I have tried on two occasions to get Jason to clarify the license for the game files (once on behalf of the Debian Games Team), but I didn't manage to get anything that was clearer than the text included above.  (See also the [relevant bug for Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=628689).)

**Comment by Mailaender** [comment]
In that case it might be best to point people to https://www.gog.com/game/tyrian_2000 who seems to have redistribution rights.

**Comment by Mailaender** [comment]
Maybe not the best idea:

```
innoextract GOG_Galaxy_Tyrian_2000.exe 
Not a supported Inno Setup installer!
```

However I deleted our tyrian-data package now and wrote https://en.opensuse.org/Tyrian instead.

**Comment by carlreinke** [comment]
You wouldn't be able to use Tyrian 2000 anyway because the data files are incompatible with Tyrian 2.x.
