### ISSUE TITLE
opentyrian doesn't launch from `/usr/bin`

### ISSUE THREAD

**Issue by algent-al** [opentyrian/opentyrian#25]
Compile the game using latest git.

`opentyrian` game doesn't launch if the executable file is located in `/usr/bin/` and the data in `/usr/share/opentyrian`
This is the error I get
```
Welcome to... >> OpenTyrian v2.1.20130907-121-g717e5b4 <<

Copyright (C) 2007-2013 The OpenTyrian Development Team

This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.  See the file GPL.txt for details.

no joysticks detected
assuming mouse detected
error: failed to open 'palette.dat': No such file or directory
error: One or more of the required Tyrian 2.1 data files could not be found.
       Please read the README file.
```

No change even if I do a symbolic link 
`opentyrian ⇒ /usr/share/opentyrian/opentyrian`

all the files must be in same directory to make the game to work.
The game is launching fine if you cd to `/usr/share/opentyrian` and then run `./opentyrian`, but not if you run it directly from:
`/usr/share/opentyrian/opentyrian`

OS: Solus

**Comment by algent-al** [comment]
A workaround for this is to use `/usr/bin` a bash script and save it as `opentyrian`.
```
#!/bin/bash

pushd /usr/share/opentyrian && ./opentyrian && popd
```

**Comment by carlreinke** [comment]
OpenTyrian looks for the data files in several places, one of which is `/usr/local/share/games/tyrian` unless configured otherwise.

If you want that to be `/usr/share/opentyrian` then you can do `make TYRIAN_DIR=/usr/share/opentyrian`.

**Comment by algent-al** [comment]
Thank you!
