### ISSUE TITLE
Ship drifts left when "fit to 4:3" or "fit to 8:5" options are used.

### ISSUE THREAD

**Issue by vanfanel** [opentyrian/opentyrian#34]
Hi there,

I have been enjoying OpenTyrian on Debian GNU/Linux for years now, but I have found out that the ship drifts to the left.

After many tries, I discovered the options causing this:
**Set `FULLSCREEN` video mode, and `FIT 4:3` or `FIT 8:5`, and start a new game to see the ship drift.**
Happens on GNU/Linux at least.

**Comment by carlreinke** [comment]
Sounds like maybe a bug in the mouse pointer position mapping code.  What's the native resolution of your display?

**Comment by vanfanel** [comment]
> Sounds like maybe a bug in the mouse pointer position mapping code. What's the native resolution of your display?

It is 1360x768.

**Comment by carlreinke** [comment]
I wasn't able to reproduce the problem, but it may be fixed in 0206a17499eda1f5be9a673b8d3e6227af2d885d.
