### ISSUE TITLE
Easy to lose cursor in the window are outside the game content

### ISSUE THREAD

**Issue by AMDmi3** [opentyrian/opentyrian#41]
With e.g. "scaling mode: center", the mouse cursor is only displayed within the small game window, while the mouse can move all around the whole X11 window, so it's possible lose the cursor in the black area as it's not displayed there.

It should be easy to fix by not allowing mouse to leave the game window (as long as it's captured, see #40), and it should probably also fix #39.

However if the mouse is not captured (#40), it would make sense to unhide the system cursor when the mouse is outside the game window.

**Comment by carlreinke** [comment]
Fixed in 8f205e6b12cb9c34905fa960416b6f661bf38ac3.

**Comment by AMDmi3** [comment]
Confirmed, thank you!
