### ISSUE TITLE
install all icons rather than just one

### ISSUE THREAD

**Issue by grawlinson** [opentyrian/opentyrian#43]
Just noticed this line in the Makefile:

https://github.com/opentyrian/opentyrian/blob/8f205e6b12cb9c34905fa960416b6f661bf38ac3/Makefile#L125

According to the [XDG Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) (more specifically, the [directory layout](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout)), multiple icon resolutions can be installed.

```diff
--- a/Makefile
+++ b/Makefile
@@ -122,7 +122,10 @@ install : $(TARGET) installdirs
        $(INSTALL_DATA) NEWS README $(DESTDIR)$(docdir)/
        $(INSTALL_DATA) linux/man/opentyrian.6 $(DESTDIR)$(man6dir)/opentyrian$(man6ext)
        $(INSTALL_DATA) linux/opentyrian.desktop $(DESTDIR)$(desktopdir)/
-       $(INSTALL_DATA) linux/icons/tyrian-32.png $(DESTDIR)$(pixmapdir)/opentyrian.png
+       for size in 22 24 32 48 128; do \
+               $(INSTALL_DATA) -D "linux/icons/tyrian-$${size}.png" \
+               "$(DESTDIR)$(pixmapdir)/hicolor/$${size}x$${size}/apps/opentyrian.png"; \
+       done;

 .PHONY : uninstall
 uninstall :
```

I'd open a pull request, but I currently have another PR open in opentyrian2000 (which is a fork of this repository), and github won't let me make a fork of this repository when I have a fork of a fork.

**Comment by carlreinke** [comment]
Fixed in 74245dbebb8f280f4229c32b65de0854e5f843d2.
