### ISSUE TITLE
SDF Main Gun not rewarded in EP4

### ISSUE THREAD

**Issue by MajorCooke** [opentyrian/opentyrian#44]
When playing on hard difficulty (not sure about the rest), SDF main gun isn't rewarded upon completing the ICESECRET mission.

**Comment by carlreinke** [comment]
As far as I can tell, this is a bug in the Tyrian 2.1 data files.  There's an event in the level script that would give the SDF Main Gun, but it's at a time code that doesn't seem to be reachable.

```
9080 82   41                         MYSTERY SPECIAL WEAPON : SDF Main Gun
4080 62   29
```

`62 29` plays the power-up sound effect.  The level ends at time code 4100.

For comparison, here's the code for giving the Mega Laser Dual earlier in the level script:

```
0130 82   15                         MYSTERY SPECIAL WEAPON : Mega Laser Dual
0130 62   29
```

**Comment by MajorCooke** [comment]
So nothing can be done then? Or was it fixed?

**Comment by carlreinke** [comment]
Unless it works in Tyrian 2.1, there's nothing to do.
