### ISSUE TITLE
Current Release build Segfaults in OpenSuse Leap 15.3.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [opentyrian/opentyrian#45]
Current Release build Segfaults in OpenSuse Leap 15.3. I have provided asset Data from GOG. I cannot get an effective back trace.

**Comment by carlreinke** [comment]
GOG has Tyrian 2000.  OpenTyrian requires Tyrian 2.1 data files.

If you want to use the Tyrian 2000 data files, consider trying [OpenTyrian 2000](https://github.com/KScl/opentyrian2000/) instead.
