### ISSUE TITLE
Unable to open the program?

### ISSUE THREAD

**Issue by iamPorter** [opentyrian/opentyrian#49]
It's weird that all of my two computers cannot open OpenTyrian! 
When on Windows 10 Pro 1809, it just flashed a window and it closed. When on MacOS Big Sur, it shows a white screen with other function running normally. What happened and how can I provide its log?

**Comment by carlreinke** [comment]
Do you have the Tyrian 2.1 data files in a location where OpenTyrian will look for them?  On Windows, this is typically either the same directory as `opentyrian.exe` or in a `data` subdirectory.

**Comment by iamPorter** [comment]
Yes. If I don't do so, Windows would show a warning that I lost something. But this time there's just a window that only exists for about 0.1s. By the way, is MacOS version contained in this project? If so, please notice my another error too.-- Sent from Nokia 6300 4Gopentyrian/opentyrian writes:
Do you have the Tyrian 2.1 data files in a location where OpenTyrian will look for them?  On Windows, this is typically either the same directory as opentyrian.exe or in a data subdirectory.

**Comment by carlreinke** [comment]
> If I don't do so, Windows would show a warning that I lost something.

I'm not talking about the `.dll` files, I'm talking about `tyrian.hdt`, `cubetxt1.dat`, etc.  You can get the data files [here](https://camanis.net/tyrian/tyrian21.zip).


> is MacOS version contained in this project?

No, there is no MacOS version in this repository.

**Comment by iamPorter** [comment]
OK now I know what’s wrong. 
But I have a suggest: why not just pack the data files with the .exe and .dll files together in the release?
Or it would be quite cumbersome to download two files. 
And it’s easy for some people to ignore notes in the readme.md and download directly from release.

-----
If I don't do so, Windows would show a warning that I lost something.
I'm not talking about the .dll files, I'm talking about tyrian.hdt, cubetxt1.dat, etc. You can get the data files here.
is MacOS version contained in this project?
No, there is no MacOS version in this repository.

**Comment by filmor** [comment]
Just for reference, the macOS version that I added in 2008 was removed here: https://github.com/opentyrian/opentyrian/commit/436bdb8fcd0260dd2a53d23f0282162fc2a9724f
I haven't used a Mac (with macOS) since about 2010, that's why it wasn't maintained, but it might be a good starting point if someone wants to try to revive it. The main changes are a Cocoa main function and an adjusted path lookup.
