### ISSUE TITLE
Rename 'OpenTyrian' Menu option to 'Setup'

### ISSUE THREAD

**Issue by OpenRift412** [opentyrian/opentyrian#51]
This is probably just an OCD thing, but it just seems a little weird to have the OpenTyrian-specific settings just labelled as 'OpenTyrian' instead of something more informative like 'Settings' or 'Setup'. In my opinion it gives the impression that it's more of just an about screen than a menu with additional settings.

Thoughts?

**Comment by carlreinke** [comment]
I agree.

Fixed in f35f4c22b49202dc7f028d229239d3c56b0e1dd3.
