### ISSUE TITLE
Sluggish mouse sensitivity problem

### ISSUE THREAD

**Issue by Buyukcaglar** [opentyrian/opentyrian#52]
Hi,
Current up to date build does not respect windows mouse sensitivity settings anymore like the previous build did, effectively rendering the game impossible to play on harder settings. This may be a side of effect of updating SDL libraries to v2 or something else, but the ship displacement on screen is now constant and painfully slow in this build.

**Comment by carlreinke** [comment]
This is a known issue with SDL relative mouse motion: https://github.com/libsdl-org/SDL/issues/5992
