### ISSUE TITLE
opentyrian 2.1.20221123 doesn't work on my system

### ISSUE THREAD

**Issue by as-muncher** [opentyrian/opentyrian#58]
Hi, I run opentyrian, even sometimes running it as administrator, and all I get is a small black window that pops up momentarily and then disappears.  I tried opening up a command prompt, executing that file, and still same thing, no extra text that I could catch, no error message.

However, I have an earlier version of opentyrian that DOES work.  I'm sorry but I'm not sure which version it is...  I'm currently on a linux system, and so when I right-click on opentyrian.exe, there's no version information.  When I open readme.txt, or credits.txt, there is no version information there, either.  or maybe I've missed it.

**Comment by as-muncher** [comment]
Ok so it's 2.1.20130907 that works on my system.  I haven't tried any later versions except the latest one from 2022-12-23 which gives the small black window briefly and doesn't run.

**Comment by as-muncher** [comment]
I think the problem is that I had to download the data files separately.  Why do it that way?  Why not just include it on the github site?

**Comment by carlreinke** [comment]
The data files are not included in the OpenTyrian release because the license for the data files is different.

**Comment by as-muncher** [comment]
@carlreinke Oh.  Well...  I'm still having a problem with compiling opentyrian on my system.  Hopefully, you can offer some suggestions.
