### ISSUE TITLE
Question: Legality with including game files

### ISSUE THREAD

**Issue by seifer7** [opentyrian/opentyrian#64]
Hi guys
I know that Tyrian has released as freeware a long time ago.
Currently OpenTyrian requires your original game files to run, but they are not included.

I have some ideas for some very big changes that would be outside the scope of being included in this project but would be a standalone fork.

**My question is would I be allowed to include the original game files (that will be modified) in the project?**

Any references/links you can dig up that can confirm or refute would be appreciated!

**Comment by carlreinke** [comment]
The freeware license for the game is a very brief and informal:

>Feel free to play it all you want and share it with friends

https://web.archive.org/web/20140808040448/http://www.freewebs.com/worldtreegames/

The graphics are available under a more liberal license but still brief and informal:

> I’m making the set available for using in your games, prototypes, animations, etc. Again, use and abuse them as desired. If you make something cool, let me know!

https://lostgarden.home.blog/2007/04/05/free-game-graphics-tyrian-ships-and-tiles/
