### ISSUE TITLE
bring back full screen mode

### ISSUE THREAD

**Issue by as-muncher** [opentyrian/opentyrian#65]
Hi, I see that I can use full screen as of opentyrian-2.1.20130907-w32, but after that, can't do full screen.  I press alt-enter and I get a Tyrian window with a thick black border, but not a true full screen.  Plus, it was kind of neat to have that very pixelated picture of the aviator and his plane.

**Comment by carlreinke** [comment]
Full screen mode definitely still exists.  It sounds like you have the "scaling mode" set to "center" in the graphics settings.  Try one of the other options.

**Comment by as-muncher** [comment]
@carlreinke Ok, maybe the 4:3 mode is what I'm more used to.  Thanks.
