### ISSUE TITLE
Debian Data File Directory

### ISSUE THREAD

**Issue by stephen-hill** [opentyrian/opentyrian#67]
Hi

I have the data files from GOG.com and I have convert all the files to lowercase.

However, I cannot find any documentation on where to put them on debian?
(I've also tried reading the source code but I couldn't figure it out)

Many Thanks
Stephen

**Comment by carlreinke** [comment]
You will not be able to use the data files from GOG because OpenTyrian requires the Tyrian 2.1 data files and GOG has Tyrian 2000.

The default location for the data files is `/usr/local/share/games/tyrian`, but the Debian package appears to use `/usr/share/games/tyrian`.

**Comment by stephen-hill** [comment]
@carlreinke Thank you for making that clear.

I have to admit, I thought v2.1 simply referred to the binary and not the public title of the game.

For those who want to play Tyrian2000, there is https://github.com/KScl/opentyrian2000
