### ISSUE TITLE
add AppImage support 

### ISSUE THREAD

**Issue by Gi-0n** [opentyrian/opentyrian#74]
In Debian derivatives the installation is easy, but for other distributions it was difficult for me to start the game. I tried to play on Manjaro Linux, at first I used the AUR repositories, they did not compile the game, then I saw a tutorial on how to unpack a .deb and use the executable to start the game. I think AppImage will be beneficial. thank you :)

**Comment by carlreinke** [comment]
Sorry, I am not going to get into the business of packaging the game for all the various Linux distributions.
