### ISSUE TITLE
Flatpak release of OpenTyrian is broken in Fedora 39, but Snap release continues to work

### ISSUE THREAD

**Issue by GhostCoder22** [opentyrian/opentyrian#75]
I played OpenTyrian all the time on Windows, but after experiencing just way too many slowdowns caused by services continuously accessing my hard drive (most likely Microsoft AntiMalware Executable), I decided it best to finally make the switch to Linux until finally landing on Fedora 38, that is until last night when it was time to do a distro upgrade to 39, which I've done through KDE Konsole.

The Flatpak release of OpenTyrain ran perfectly on Fedora 38 KDE Desktop, but after upgrading the distro to Fedora 39, OpenTyrian had completely stopped working. Sometimes, all the game will do is show the title before gracefully exiting back to the desktop while other times it fails to just start.

After upgrading my distro from Fedora 38 to Fedora 39, I've tried installing OpenTyrian Flatpak using the following two installation methods:
- Installing Flatpak release of OpenTyrian directly from Discover
- Installing from Konsole with command **flatpak install flathub com.github.opentyrian.OpenTyrian**

Unfortunately, I now firmly believe the Flatpak release of OpenTyrian is broken in Fedora 39. The Snap release of OpenTyrian however seems to work perfectly so far.

**Comment by carlreinke** [comment]
You'll need to file an issue against the [Flathub repo](https://github.com/flathub/com.github.opentyrian.OpenTyrian).  The OpenTyrian project itself does not provide any Linux packages.

**Comment by GhostCoder22** [comment]
> You'll need to file an issue against the [Flathub repo](https://github.com/flathub/com.github.opentyrian.OpenTyrian). The OpenTyrian project itself does not provide any Linux packages.

Over at [https://github.com/flathub/com.github.opentyrian.OpenTyrian](https://github.com/flathub/com.github.opentyrian.OpenTyrian), right?

**Comment by carlreinke** [comment]
Right.
